# TidyPy is a Python lint tool. https://pypi.org/project/tidypy/
# This file controls what checks to apply to our code.

[tool.tidypy]
exclude = [ "venv"]

[tool.tidypy.pydocstyle]
disabled = [
    # D212 and D213 have to do with multi-line docstrings: should they
    # start on the same line or next? I chose same line.
    "D213",
    # D203 says "1 blank line required before class docstring" but
    # that just feels extraneous to me, especially with D213.
    "D203",
]
